[package]
name = "genoio-io"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flate2 = "1"
genoio-core = { path = "../genoio-core" }
rust-htslib = { version = "1.0.0", default-features = false }
rusqlite = { version = "0.32", features = ["bundled"] }
zstd = "0.13"

[dev-dependencies]
serde_json = "1"

[lib]
path = "src/lib.rs"
