# pattern: Functional Core

from typing import Any

# Type surface for the PyO3 extension module built by maturin. The runtime
# implementation is the compiled shared object; this stub keeps static checking
# aware of the Rust functions imported by `genoio._api`.

class RustInvalidSourceError(Exception): ...
class RustUnsupportedRepresentationError(Exception): ...
class RustInvalidOptionError(Exception): ...
class RustMissingDataError(Exception): ...
class RustSampleFilterError(Exception): ...
class RustInternalError(Exception): ...
class ArrowMetadataFrame: ...

def backend_name() -> str: ...
def validate_read_support(format: str, kind: str, dosage: str, sparse: bool) -> None: ...
def read_metadata(format: str, members: dict[str, str]) -> dict[str, Any]: ...
def read_dense(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
def read_sparse(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
def read_haplotypes_dense(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
def read_haplotypes_sparse(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
