from typing import Any

# Type surface for the PyO3 extension module built by maturin. The runtime
# implementation is the compiled shared object; this stub keeps static checking
# aware of the Rust functions imported by `genoio._api`.

def read_metadata(format: str, members: dict[str, str]) -> dict[str, Any]: ...
def read_dense(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
def read_sparse(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
def read_haplotypes_dense(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
def read_haplotypes_sparse(format: str, members: dict[str, str], options: dict[str, Any]) -> dict[str, Any]: ...
