[package]
name = "genoio-py"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "genoio_py"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
genoio-core = { path = "../genoio-core" }
genoio-io = { path = "../genoio-io" }
numpy = "0.29"
pyo3 = { version = "0.29", features = ["extension-module"] }
serde_json = "1"
